In this notebook, we will elucidate various methodologies for designing and analyzing experiments, specifically A/B tests, using panel data, employing an illustrative example. 

Panel data typically comprises a collection of time series data pertaining to a particular metric (e.g., yearly revenue) across various units (e.g., states). Moreover, this data often undergoes modifications, commonly referred to as treatments (e.g., a promotional campaign for a subscription service). Our primary objective is to draw useful conclusions from the data.

Our overarching aim is to exemplify two core tasks:

1. **Experimental Design**: In this context, we seek to allocate available units into treatment and control groups. The treated group of units receives a specific treatment, while the control group remains untreated.

2. **Inference on Observational Data**: Here, treatment assignments are already provided, and our goal is to draw conclusions, such as the effectiveness or ineffectiveness of the treatment, from the available data, often referred to as observational data.

To begin, we will initiate by loading the "paneldata" package.

In [1]:
import sys
sys.path.insert(0, '..')
from panel_exp.panel_data import long_df_to_paneldataset, PanelDataset, TimePeriod

/Users/ppavuluri/Desktop/panel_exp/panel_exp/examples/../panel_exp/panel_data.py:527: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (
/Users/ppavuluri/Desktop/panel_exp/panel_exp/examples/../panel_exp/panel_data.py:536: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (

We are importing historical quarterly GDP data for various states in the United States into a pandas dataframe [AugSynth](#ben2021augmented).

The dataframe consists of rows, each with the following columns:

- `lngdp`: This column contains the natural logarithm of the state's GDP revenue for a specific quarter.

- `year_qtr`: This column represents the year and corresponding quarter in a numerical format. For example, "1990.25" corresponds to the second quarter of the year 1990.

- `state`: This column specifies the U.S. state associated with the data entry.

### References

- [AugSynth](#ben2021augmented): Ben-Michael, E., Feller, A., Rothstein, J. (2021). The augmented synthetic control method. Journal of the American Statistical Association.

In [2]:
import pandas as pd 
import numpy as np

long_df = pd.read_csv('kansas_parsed.csv', index_col=0)
long_df.iloc[:,0] = long_df.iloc[:,0].apply(lambda x: np.exp(x))
long_df.head()

      lngdp  treated  fips  year_qtr    state
1  71610.00        0     1   1990.00  Alabama
2  72718.25        0     1   1990.25  Alabama
3  73826.50        0     1   1990.50  Alabama
4  74934.75        0     1   1990.75  Alabama
5  76043.00        0     1   1991.00  Alabama

In [3]:
# Remove the treated unit
# In our working example, we treat the state of "Kansas" as the treated unit, while the other states are treated as control units. 
# long_df = long_df[long_df.state != "Kansas"]

We are presently transforming the pandas dataframe into a paneldata object. A paneldata object encompasses the following components:

- `wide_data`: This is a pandas dataframe structured as `n_units` (number of units) by `n_time` (number of time periods). Each row corresponds to a specific unit (e.g., a state), and each column represents a particular time period. This dataframe contains the actual data observations.

- `treated_periods`: This is a list that contains all of the time periods during which a treatment or intervention was applied. For instance, if the dataframe includes data for the year 2000, "2000.00" from the provided paneldata, it would be included in this list.

- `treated_units`: This is a list that contains all of the units (e.g., states) that have undergone a treatment or intervention. For example, if the state of Kansas received treatment, it would be listed in this component.

In [4]:
# Create a panel dataset
panel_data = long_df_to_paneldataset(long_df, "year_qtr", "state", "lngdp", ["Kansas"], 2000)
print(panel_data.summarize())

        Panel Dataset Summary
        ---------------------
        Number of time points: 105
        Number of units: 50
        Number of treated units: 1
        Treated units: ['Kansas']
        Treated periods: [TimePeriod(start=2000, end=None)]

In [5]:
panel_data.wide_data

# convert a dataframe to a numpy matrix
panel_data.wide_data.values

(panel_data.wide_data.values).shape

panel_data.wide_data

year_qtr,1990.00,1990.25,1990.50,1990.75,1991.00,1991.25,1991.50,1991.75,1992.00,1992.25,...,2013.75,2014.00,2014.25,2014.50,2014.75,2015.00,2015.25,2015.50,2015.75,2016.00
state,,,,,,,,,,,,,,,,,,,,,
Alabama,11.178990,11.194348,11.209473,11.224373,11.239054,11.256060,11.272782,11.289229,11.305409,11.315520,...,12.163572,12.154069,12.170471,12.188748,12.188642,12.194218,12.206887,12.215731,12.215716,12.220345
Alaska,10.128230,10.100318,10.071605,10.042042,10.011579,10.016839,10.022070,10.027275,10.032452,10.038270,...,10.984377,10.979564,10.981404,10.974883,10.950105,10.892768,10.907368,10.881795,10.852865,10.820598
Arizona,11.165239,11.174841,11.184352,11.193773,11.203107,11.234388,11.264720,11.294160,11.322757,11.342570,...,12.525355,12.530508,12.538426,12.556251,12.559402,12.574943,12.583954,12.588235,12.603969,12.608035
Arkansas,10.563078,10.581597,10.599780,10.617638,10.635182,10.655693,10.675792,10.695495,10.714818,10.728868,...,11.654850,11.663042,11.676642,11.684481,11.691666,11.676251,11.689061,11.696871,11.695947,11.695297
California,13.558629,13.563976,13.569294,13.574584,13.579846,13.585310,13.590743,13.596147,13.601522,13.607416,...,14.643806,14.648005,14.666093,14.686874,14.693069,14.715586,14.732883,14.739666,14.748138,14.759022
Colorado,11.232828,11.246610,11.260205,11.273618,11.286853,11.310197,11.333009,11.355312,11.377129,11.400778,...,12.590719,12.600275,12.621359,12.642216,12.655819,12.650778,12.661061,12.665139,12.666812,12.659985
Connecticut,11.514614,11.517868,11.521112,11.524345,11.527568,11.538067,11.548457,11.558740,11.568918,11.573449,...,12.406005,12.394525,12.400463,12.413091,12.421668,12.437823,12.454954,12.452155,12.459117,12.464155
Delaware,9.899881,9.922432,9.944486,9.966063,9.987185,10.000444,10.013530,10.026446,10.039198,10.045746,...,11.060227,11.067060,11.094102,11.115161,11.119453,11.141296,11.156779,11.145839,11.157007,11.146647
Florida,12.455231,12.465968,12.476592,12.487104,12.497506,12.513263,12.528776,12.544051,12.559096,12.576275,...,13.607421,13.611044,13.626679,13.642127,13.655397,13.675450,13.688342,13.705091,13.721159,13.717683
Georgia,11.854001,11.866567,11.878977,11.891235,11.903345,11.923945,11.944130,11.963915,11.983317,12.001268,...,13.046430,13.052076,13.072965,13.091615,13.102703,13.115995,13.130829,13.142554,13.149813,13.169892
Hawaii,10.390041,10.403952,10.417673,10.431207,10.444561,10.457373,10.470022,10.482514,10.494851,10.499015,...,11.234956,11.232841,11.247122,11.262745,11.271160,11.296298,11.307315,11.315145,11.326439,11.335603
Idaho,9.798349,9.810056,9.821627,9.833065,9.844374,9.867705,9.890504,9.912794,9.934599,9.964065,...,11.033873,11.032904,11.048920,11.059928,11.080557,11.091788,11.096895,11.099922,11.096197,11.111492
Illinois,12.539035,12.547470,12.555835,12.564130,12.572357,12.587633,12.602680,12.617504,12.632111,12.643349,...,13.508251,13.502342,13.525085,13.539371,13.545102,13.549877,13.557056,13.574031,13.572858,13.577407
Indiana,11.616023,11.624505,11.632915,11.641255,11.649526,11.671264,11.692539,11.713371,11.733778,11.748492,...,12.655762,12.675551,12.686698,12.705307,12.709493,12.709937,12.722399,12.728007,12.735612,12.738989
Iowa,10.935265,10.943353,10.951377,10.959336,10.967232,10.984029,11.000549,11.016800,11.032791,11.038898,...,12.006755,12.016787,12.052321,12.063028,12.067448,12.080334,12.098671,12.113667,12.119490,12.114560
Kansas,10.856573,10.866676,10.876678,10.886581,10.896387,10.909825,10.923084,10.936169,10.949086,10.958057,...,11.883088,11.873714,11.898501,11.923690,11.935451,11.914824,11.931662,11.932175,11.929687,11.911064
Kentucky,11.133304,11.145172,11.156900,11.168493,11.179953,11.200158,11.219963,11.239383,11.258433,11.271526,...,12.116093,12.113826,12.131446,12.140627,12.146630,12.143851,12.161745,12.170357,12.182814,12.161415
Louisiana,11.463494,11.465766,11.468033,11.470295,11.472551,11.459047,11.445358,11.431479,11.417405,11.430999,...,12.369738,12.370816,12.400343,12.421849,12.417265,12.397961,12.394389,12.394596,12.377535,12.371494
Maine,10.054318,10.055640,10.056959,10.058277,10.059593,10.069701,10.079707,10.089614,10.099424,10.108355,...,10.897498,10.900916,10.913214,10.928704,10.945635,10.937348,10.955393,10.960514,10.972019,10.978524
Maryland,11.633682,11.639411,11.645107,11.650770,11.656402,11.665258,11.674036,11.682738,11.691364,11.703794,...,12.750389,12.747196,12.765165,12.781157,12.778836,12.802943,12.804753,12.813618,12.825458,12.832930
Massachusetts,11.979831,11.981746,11.983657,11.985565,11.987469,11.997847,12.008119,12.018286,12.028350,12.037405,...,13.015860,13.012850,13.021205,13.051681,13.065323,13.082202,13.095915,13.101311,13.122123,13.118357
Michigan,12.170979,12.176935,12.182855,12.188741,12.194592,12.212562,12.230214,12.247560,12.264610,12.281341,...,12.985952,12.982566,13.001149,13.018948,13.024914,13.044439,13.062282,13.072440,13.081877,13.079877
Minnesota,11.540122,11.548227,11.556267,11.564243,11.572156,11.591792,11.611050,11.629944,11.648487,11.655945,...,12.644853,12.645681,12.664241,12.680345,12.684134,12.691624,12.695027,12.702228,12.718884,12.708147
Mississippi,10.565067,10.578553,10.591861,10.604993,10.617956,10.637045,10.655776,10.674163,10.692218,10.710945,...,11.549537,11.545470,11.561077,11.560028,11.566163,11.562116,11.571902,11.580556,11.581481,11.589257
Missouri,11.547964,11.561382,11.574622,11.587690,11.600588,11.614520,11.628261,11.641815,11.655189,11.663004,...,12.538784,12.527518,12.544985,12.560956,12.570073,12.576470,12.589006,12.597834,12.593370,12.598824
Montana,9.491149,9.503029,9.514769,9.526373,9.537844,9.556798,9.575400,9.593662,9.611597,9.630119,...,10.684577,10.697452,10.719450,10.723201,10.722981,10.724104,10.745615,10.736223,10.727948,10.732476
Nebraska,10.426262,10.440091,10.453731,10.467188,10.480466,10.498560,10.516333,10.533795,10.550957,10.558381,...,11.575111,11.608608,11.629641,11.629081,11.643348,11.651983,11.663352,11.663559,11.656757,11.660146
Nevada,10.341097,10.355566,10.369828,10.383890,10.397757,10.422356,10.446364,10.469809,10.492718,10.519990,...,11.775067,11.780912,11.789223,11.803930,11.821153,11.838792,11.855515,11.868584,11.870761,11.870775
New Hampshire,10.076095,10.086507,10.096811,10.107010,10.117106,10.132822,10.148295,10.163532,10.178540,10.188272,...,11.147844,11.145406,11.171041,11.176235,11.199118,11.195416,11.217157,11.229541,11.247800,11.247996
New Jersey,12.275398,12.284174,12.292874,12.301499,12.310050,12.319980,12.329813,12.339551,12.349194,12.359556,...,13.194626,13.195337,13.196663,13.209513,13.216234,13.218964,13.240401,13.250106,13.250602,13.255903
New Mexico,10.188666,10.222805,10.255816,10.287772,10.318738,10.337888,10.356679,10.375123,10.393233,10.425179,...,11.427455,11.432604,11.452326,11.470738,11.476542,11.438665,11.446925,11.444422,11.432301,11.426463
New York,13.108654,13.110752,13.112846,13.114936,13.117021,13.128202,13.139260,13.150196,13.161015,13.169541,...,14.125722,14.123333,14.135762,14.154319,14.170992,14.177905,14.196119,14.205511,14.194526,14.211853
North Carolina,11.846952,11.858890,11.870687,11.882347,11.893872,11.915784,11.937225,11.958217,11.978777,11.992287,...,13.050003,13.056679,13.062726,13.078976,13.089102,13.111588,13.122329,13.130480,13.138211,13.147727
North Dakota,9.350885,9.354830,9.358760,9.362675,9.366575,9.392016,9.416826,9.441035,9.464672,9.467634,...,10.912449,10.943694,10.998594,11.019498,11.025247,10.966334,10.947626,10.935550,10.912066,10.878047
Ohio,12.334523,12.341711,12.348847,12.355933,12.362970,12.380630,12.397983,12.415041,12.431813,12.440712,...,13.263330,13.266098,13.288794,13.314441,13.316559,13.315384,13.322531,13.325688,13.333838,13.327094
Oklahoma,10.964831,10.972701,10.980510,10.988259,10.995948,11.006693,11.017325,11.027845,11.038255,11.051600,...,12.159479,12.170870,12.198000,12.223126,12.206538,12.169870,12.166151,12.156399,12.130034,12.099767
Oregon,10.943163,10.955790,10.968259,10.980574,10.992740,11.009220,11.025434,11.041389,11.057093,11.080545,...,12.206558,12.195381,12.215795,12.241416,12.248246,12.274142,12.282691,12.299235,12.309274,12.328666
Pennsylvania,12.410160,12.420182,12.430104,12.439929,12.449658,12.463944,12.478029,12.491919,12.505618,12.516541,...,13.415249,13.416442,13.431688,13.447958,13.455139,13.457575,13.467802,13.473219,13.482110,13.466130
Rhode Island,9.983407,9.984261,9.985114,9.985966,9.986817,9.997422,10.007915,10.018300,10.028577,10.038466,...,10.871896,10.877424,10.885529,10.896369,10.912631,10.922371,10.934267,10.938752,10.951333,10.940933
South Carolina,11.084555,11.095404,11.106137,11.116756,11.127263,11.141311,11.155164,11.168828,11.182308,11.197194,...,12.128273,12.133486,12.159474,12.171098,12.178953,12.199169,12.211647,12.228612,12.238438,12.239159
South Dakota,9.454854,9.473589,9.491979,9.510037,9.527775,9.548490,9.568784,9.588674,9.608176,9.628442,...,10.706789,10.731013,10.739717,10.722386,10.721570,10.740150,10.757818,10.777309,10.785932,10.769306
Tennessee,11.451975,11.470720,11.489119,11.507187,11.524933,11.550424,11.575280,11.599534,11.623214,11.640764,...,12.583975,12.589854,12.603378,12.615779,12.625299,12.643721,12.660439,12.675554,12.683790,12.692860
Texas,12.845141,12.854747,12.864262,12.873687,12.883024,12.897420,12.911611,12.925604,12.939404,12.955705,...,14.265197,14.268559,14.291012,14.309878,14.302607,14.294107,14.295579,14.293019,14.280231,14.268792
Utah,10.349743,10.367599,10.385142,10.402382,10.419331,10.434888,10.450206,10.465294,10.480157,10.501204,...,11.814244,11.834973,11.849383,11.862836,11.874348,11.892129,11.908892,11.916843,11.930530,11.945733
Vermont,9.365119,9.366382,9.367643,9.368903,9.370161,9.387168,9.403890,9.420338,9.436519,9.446222,...,10.275430,10.263676,10.276636,10.298094,10.317450,10.307719,10.315100,10.329670,10.330257,10.337864
Virginia,11.884289,11.894791,11.905184,11.915470,11.925651,11.938633,11.951448,11.964101,11.976597,11.990181,...,13.026355,13.020118,13.033609,13.044400,13.053039,13.062078,13.081316,13.093725,13.100406,13.092939
Washington,11.683849,11.699021,11.713967,11.728692,11.743204,11.760086,11.776689,11.793020,11.809089,11.823910,...,12.930270,12.936805,12.954397,12.974777,12.987608,12.998463,13.015128,13.032802,13.038360,13.058876
West Virginia,10.231135,10.243116,10.254954,10.266654,10.278219,10.289481,10.300618,10.311632,10.322527,10.334547,...,11.198968,11.185379,11.210671,11.222292,11.220405,11.185213,11.209629,11.206984,11.194839,11.172630
Wisconsin,11.515283,11.526537,11.537667,11.548674,11.559561,11.578933,11.597937,11.616587,11.634895,11.650380,...,12.565340,12.558710,12.579583,12.591560,12.599546,12.611591,12.621290,12.634733,12.639937,12.640812
Wyoming,9.449751,9.455089,9.460398,9.465680,9.470934,9.474818,9.478687,9.482541,9.486380,9.497922,...,10.616070,10.620864,10.640269,10.646520,10.633160,10.583220,10.588325,10.582155,10.560463,10.543076


In this section, we delve into the discussion of several randomization strategies. Within each of these strategies, we employ random assignment to allocate units from the panel data into either "Treatment" or "Control" groups. Such randomization strategies build robustness into our models to handle uncertainity in the potential outcomes and reduces the risk of confounding.

By employing a variety of randomization strategies, we distribute different states (considered as pre-treatment units) into two distinct groups. For instance, in one randomization, Massachusetts may be assigned to the "Treatment" group, while Alabama may be assigned to the "Control" group.

In [4]:
from panel_exp.design import CompleteRandomization, ThinningDesign, Rerandomization, QuickBlock, greedy_match_markets
from panel_exp.design.design_metrics import imbalance

**Complete Randomization**: In this approach, we implement a fully random allocation strategy. A fixed proportion of the units, such as 50% (e.g., denoted as 0.5), is chosen entirely at random and assigned to the "Treatment" group, while the remaining half is assigned to the "Control" group.

The outcome of this assignment process is a paneldata object. After this assignment, we can conveniently access the units designated as treated units using the "treated_units" field, as shown below:

In [8]:
panel_data = long_df_to_paneldataset(long_df, "year_qtr", "state", "lngdp")

cr = CompleteRandomization(treatment_probability=0.5)
paneldata_post_assignment = cr.assign(panel_data)
paneldata_post_assignment.treated_units

We measure the performance of randomization strategy using the imbalance between the treatment and control groups -- higher imbalance correlates with worse generalization performance, i.e., low level of robustness. This helps to make the groups more comparable and reduces the risk of confounding, which can lead to incorrect causal inferences.

Let $x_i \in \mathbb{R}^d$ denote the covariates of unit $i \in \{1, 2, \cdots, n\}$. Given a treatment assignment $z \in \{0, 1\}^n$ indicating the assignment of $n$ units to treatment or control groups, imbalance is measured using the following function:

$$ \text{imbalance}(z) = \frac{1}{d} \left\lVert \sum_{i=1}^n \frac{x_i \mathbb{1} \{ i \text{ is assigned treatment} \}}{\sum_{j = 1}^n \mathbb{1} \{ j \text{ is assigned treatment} \}} - \sum_{i=1}^n \frac{x_i \mathbb{1} \{ i\text{ is assigned control} \}}{\sum_{j = 1}^n \mathbb{1} \{ j\text{ is assigned control} \} } \right\rVert^2 $$

It can also be written as:
$$ \text{imbalance}(z) = \frac{1}{d} \left\lVert \frac{\sum_{i=1}^n x_i z_i}{\sum_{j=1}^n z_j} -  \frac{\sum_{i=1}^n x_i (1-z_i)}{\sum_{j=1}^n (1-z_j)} \right\rVert^2 $$

In [9]:
imbalance(paneldata_post_assignment)

0.10683239395691718

In [10]:
# # We should have 49 units here after dropping Kansas
# # no treated units and no treated periods
# x = TimePeriod()
# x.end  = 2015.25
# ppd = panel_data.drop_period(x)
# ppd.wide_data
# panel_data.summarize

**ThinningDesign**: In this design, the main idea is to partition the units into two groups such that the imbalance function with $l_{\infty}$ error is minimized, instead of the $l_2$ error as defined in the works of [Thinning](#dwivedi2021), [OnlineDesign](#arbour2022).

$$ \text{imbalance}(z) =  \max \left( \frac{\sum_{i=1}^n x_i z_i}{\sum_{j=1}^n z_j} -  \frac{\sum_{i=1}^n x_i (1-z_i)}{\sum_{j=1}^n (1-z_j)} \right) $$


### References
- [Thinning](#dwivedi2021): Dwivedi, R., & Mackey, L. (2021). Kernel Thinning. In Conference on Learning Theory (pp. 1753-1753). PMLR.
- [OnlineDesign] (#arbour2022) :Arbour, D., Dimmery, D., Mai, T., & Rao, A. (2022). Online Balanced Experimental Design. In International Conference on Machine Learning (pp. 844-864). PMLR.

In [11]:
dm = ThinningDesign(treatment_probability=0.5)
imbalance(cr.assign(panel_data))

0.060949883931042566

**Rerandomization**: We repeat the process of randomization (e.g., using CompleteRandomization or ThinningDesign) a fixed number of times and pick the randomized assignment with lowest imbalance.

We generate the treatment vector $z_t \in \{ 0, 1 \}^n$ for the $n$ units repeatedly over $T$ times, i.e., $t \in \{1, 2, \cdots, T\}$. The treatment vectors $z_t$ can be generated through any of the previously discussed randomized strategies as shown below using the argument `base_randomizer`. Finally, we pick the vector $z_t$ that obtains the minimum imbalance:

$$z^* = \arg \min_{t \in \{1, 2, \cdots, T\}} \text{imbalance}(z_t)$$

In [12]:
rerand_dm = Rerandomization(
    treatment_probability=0.5, 
    target_imbalance=1e-4, 
    max_iter=10_000, 
    base_randomizer_cls=CompleteRandomization
)
imbalance(rerand_dm.assign(panel_data))

rerand_dm = Rerandomization(
    treatment_probability=0.5, 
    target_imbalance=1e-4, 
    max_iter=10_000, 
    base_randomizer_cls=ThinningDesign
)
imbalance(rerand_dm.assign(panel_data))

9.923028741432388e-05

**Quickblock**: It involves creating subgroups within a given dataset based on available units to ensure that treatment and control groups have similar distributions of these units [Quickblock](#higgins2016). 

### References

- [Quickblock](#higgins2016): Higgins, M. J., Sävje, F., & Sekhon, J. S. (2016). Improving massive experiments with threshold blocking. Proceedings of the National Academy of Sciences, 113(27), 7369-7376.

In [13]:
qb = QuickBlock(treatment_probability=0.5)
imbalance(qb.assign(panel_data))

/opt/homebrew/lib/python3.10/site-packages/sklearn/neighbors/_distance_metric.py:10: FutureWarning: sklearn.neighbors.DistanceMetric has been moved to sklearn.metrics.DistanceMetric in 1.0. This import path will be removed in 1.3
  warnings.warn(

0.019437637472915256

In this section, we show the performance of the synthetic control method called AugSynth. AugSynth expresses panel data associated with a fixed treated unit (e.g., Kansas) with respect to the remaining units (e.g., other states) using a linear model.

In [43]:
# !pip3 install cmake

In [44]:
# !pip3 install osqp==0.6.1

In [45]:
# !pip3 install cvxpy

In [46]:
from __future__ import annotations
import numpy as np
import pandas as pd
import scipy.stats as st
from dataclasses import dataclass

from matplotlib import pyplot as plt
from typing import Dict, Optional
from abc import (
  ABC,
  abstractmethod,
)

from panel_exp.panel_data import long_df_to_paneldataset
from panel_exp.methods.tbr import TBR
from panel_exp.methods.scm import SyntheticControl, AugSynth

Here are additional details:

**Data**:
- The dataset contains time-series data for multiple states.
- Recall that the main metric of interest is denoted by "lngdp", GDP of the particular state in a given quarter.
- The dataset spans multiple years, covering a defined observation period.

**Treatment**:
- In the year 2000, a treatment or intervention was implemented.
- This treatment was specifically applied to the state of "Kansas."

**Plot**:
- The analysis involves the creation of two curves: the "Observed" curve and the "Inferred" curve.
- Both curves are plotted on the same graph.
- The y-axis of the graph represents the variable "lngdp."
- The x-axis is normalized, meaning it is scaled in a way that allows for a uniform comparison across time.
- The treatment year, 2000, is indicated on the x-axis.
- The statement "the treatment at '2000' roughly corresponds to '40%' of total duration" suggests that the treatment duration, starting in 2000, constitutes approximately 40% of the entire observation period.

This analysis appears to involve evaluating the impact of the treatment on the economic output of Kansas compared to other states, with both observed and inferred curves illustrating the trends in "lngdp" over time.

The first plot shows both the cuves on the same figure. The second plot shows the difference between the curves vs time, while the third plot shows the **cumulative** difference vs time.

In [15]:
panel_data = long_df_to_paneldataset(long_df, "year_qtr", "state", "lngdp")

cr = CompleteRandomization(treatment_probability=0.5)
td = ThinningDesign(treatment_probability=0.5)
gm = greedy_match_markets()

design = [cr,td,gm][2]

test_whitelist = ['Kansas']

#to make test whitelist strictly inclusive, you must pass test_blacklist in the below manner (i.e. include all dmas not part of test_whitelist)
test_blacklist = [geo for geo in panel_data.units.tolist() if geo not in test_whitelist]

paneldata_post_assignment = design.assign(panel_data=panel_data,test_whitelist=test_whitelist,test_blacklist=test_blacklist)

running iteration 1
running iteration 2
running iteration 3
running iteration 4
running iteration 5
running iteration 6
running iteration 7
running iteration 8
running iteration 9
running iteration 10
running iteration 11
running iteration 12
running iteration 13
running iteration 14
running iteration 15
running iteration 16
running iteration 17
running iteration 18
running iteration 19
running iteration 20

/Users/ppavuluri/Desktop/panel_exp/panel_exp/examples/../panel_exp/panel_data.py:515: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  df = df.pivot(columns=time_column, values=value_column)

In [16]:
print('Test group: %s \n\nControl group: %s' %(paneldata_post_assignment.treated_units, [unit for unit in paneldata_post_assignment.units if unit not in paneldata_post_assignment.treated_units]))

Test group: ['Kansas']

Control group: ['Alaska', 'Idaho', 'Mississippi', 'Nebraska', 'New Mexico', 'North Dakota', 'Oklahoma', 'Oregon', 'Pennsylvania', 'South Carolina', 'West Virginia', 'Wyoming']

In [49]:
test = paneldata_post_assignment.treated_units
control = [unit for unit in paneldata_post_assignment.units if unit not in paneldata_post_assignment.treated_units]

trimmed_long_df = long_df[long_df.state.isin(test+control)]

panel_data = long_df_to_paneldataset(trimmed_long_df, "year_qtr", "state", "lngdp", test, [2000])
asynth = AugSynth()
synth = SyntheticControl()
synth.run_analysis(panel_data)
synth.plot()

SolverError: Either candidate conic solvers (['SCIPY']) do not support the cones output by the problem (SOC, NonNeg, Zero), or there are not enough constraints in the problem.

Matching Design
Expose ACS (Lupinov)
Uncertainity Estimation Conformal Inference